server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavuRepository/Microservices-Practices
          #search-paths: spring-config-store/*service'
